name: Build and Deploy Documentation

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  
on:
  push:
    branches:
      - main  # Set this to the branch containing your docs
  pull_request:
    branches:
      - main  # Set this to the branch containing your docs

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures history is fully cloned

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set this to your Python version

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Build docs
      run: |
        poetry run sphinx-build -b html docs/ _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        publish_branch: gh-pages  # Ensure this is your target branch for GitHub Pages
